name: credo_p2p
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  
  cupertino_icons: ^1.0.2

  #For currency input
  currency_text_input_formatter: ^2.1.5

  dartz: ^0.10.0

  #For checking internet connection
  data_connection_checker: ^0.3.4

  #For http requests
  dio: ^4.0.0
  
  #Onboarding screen dots
  dots_indicator: ^2.0.0
  
  #For checking the objects by their properties
  equatable: ^2.0.3

  flutter:
    sdk: flutter

  #Main business logic handler
  flutter_bloc: ^8.0.0

  #For saving tokens locally
  flutter_secure_storage: ^4.2.1

  #For loading widget
  flutter_spinkit: ^5.1.0
    
  #For rendering svg pictures
  flutter_svg: ^0.22.0

  freezed: ^0.14.5

  freezed_annotation: ^0.15.0

  get_it: ^7.2.0

  #For dependency injection
  injectable: ^1.5.0

  #For pin code and face id
  local_auth: ^1.1.8

  #Logger feature
  logger: ^1.1.0

  #Phone number formatter
  mask_text_input_formatter: ^2.0.0

  #For rounded circular indicator
  percent_indicator: ^3.4.0

  #For entering pin code (textfield)
  pinput: ^1.2.0

  #For internet connection handler
  retry: ^3.1.0

  #For stacked coumn charts
  syncfusion_flutter_charts: ^19.3.54
  
dev_dependencies:

  build_runner:

  flutter_test:
    sdk: flutter

  injectable_generator: ^1.5.2
  
  lint: ^1.7.2

  

flutter:

  uses-material-design: true
  
  assets:
    - assets/
    - assets/bottom_nav_bar/
    - assets/onboarding/
    - assets/login/
    - assets/avatar/
    - assets/profile/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          style: normal
