name: credo_p2p
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  
  #Onboarding screen dots
  dots_indicator: ^2.0.0
  
  flutter:
    sdk: flutter
    
  #For rendering svg pictures
  flutter_svg: ^0.22.0

  #Phone number formatter
  mask_text_input_formatter: ^2.0.0

  #For entering pin code (textfield)
  pinput: ^1.2.0

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.7.2

flutter:

  uses-material-design: true
  
  assets:
    - assets/onboarding/
    - assets/login/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          style: normal
